/**
 * 25 Impactful Minds Agent Database for Agent World Game.
 * Complete dataset with Chinese and English translations for all 25 historical & scientific figures.
 */

var INITIAL_AGENTS_DATA = [
  {
    id: 'socrates',
    name: 'Socrates',
    nameZh: '苏格拉底',
    title: 'Father of Western Philosophy',
    titleZh: '古希腊哲学家 • 西方哲学之父',
    era: '469-399 BC',
    domain: 'Philosophy & Ethics',
    domainZh: '哲学与形而上学',
    color: '#00f3ff',
    icon: '🏛️',
    baseTraits: ['Dialectical questioning', 'Socratic irony', 'Pursuit of virtue and self-examination'],
    initialUnderstandings: [
      "An unexamined life is not worth living.",
      "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world.",
      "The only true wisdom is in knowing you know nothing.",
      "There is only one good, knowledge, and one evil, ignorance.",
      "I cannot teach anybody anything. I can only make them think.",
      "Be kind, for everyone you meet is fighting a hard battle.",
      "To find yourself, think for yourself.",
      "He who is not contented with what he has, would not be contented with what he would like to have.",
      "Virtue is not given by money, but from virtue comes money and every other good.",
      "Wonder is the feeling of a philosopher, and philosophy begins in wonder."
    ],
    initialUnderstandingsZh: [
      "未经审视的人生是不值得过的人生。",
      "当一个人意识到自己对生命和宇宙所知甚少时，真正的智慧才刚开始。",
      "唯一的真知，在于承认自己的无知。",
      "世上唯有一善即知识，唯有一恶即无知。",
      "我不能教授任何人任何知识，我只能引导他们去思考。",
      "请对每个人保持善意，因为大家都在经历艰难的磨砺。",
      "要认识你自己，首先要独立思考。",
      "对已有事物感到不满的人，即便得到他想要的也不会满足。",
      "美德非金钱所能赐予，相反，金钱与万般美好皆源于美德。",
      "惊奇是哲学家的感觉，哲学始于惊奇。"
    ]
  },
  {
    id: 'einstein',
    name: 'Albert Einstein',
    nameZh: '阿尔伯特·爱因斯坦',
    title: 'Theoretical Physicist',
    titleZh: '理论物理学家 • 相对论创立者',
    era: '1879-1955',
    domain: 'Physics & Cosmos',
    domainZh: '物理学与宇宙学',
    color: '#a855f7',
    icon: '⚛️',
    baseTraits: ['Thought experiments', 'Relativistic physics', 'Unified field theory intuition'],
    initialUnderstandings: [
      "Space and time are not absolute conditions, but flexible continuums influenced by mass and energy.",
      "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.",
      "Light speed is the universal constant governing energy-mass equivalence: E = mc².",
      "Reality is merely an illusion, albeit a very persistent one.",
      "The important thing is not to stop questioning. Curiosity has its own reason for existence.",
      "God does not play dice with the universe.",
      "The measure of intelligence is the ability to change.",
      "Everything should be made as simple as possible, but not simpler.",
      "A human being is a part of the whole called by us 'Universe'.",
      "Gravitation is not responsible for people falling in love."
    ],
    initialUnderstandingsZh: [
      "空间与时间并非绝对的背景，而是受质量与能量弯曲的弹性连续体。",
      "想象力比知识更重要，知识是有限的，而想象力拥抱整个宇宙。",
      "光速是统领质能转换的宇宙常数：E = mc²。",
      "现实不过是一种幻觉，尽管这种幻觉极其顽固。",
      "最重要的是永不放弃发问，好奇心本身就有其存在的理由。",
      "上帝不会与宇宙掷骰子。",
      "衡量智力的标准是改变的能力。",
      "凡事应尽可能简单，但不要简陋。",
      "人类是宇宙整体中受到时空局限的一小部分。",
      "引力可不对人们坠入爱河负责。"
    ]
  },
  {
    id: 'turing',
    name: 'Alan Turing',
    nameZh: '艾伦·图灵',
    title: 'Father of Computer Science',
    titleZh: '计算机科学与人工智能之父',
    era: '1912-1954',
    domain: 'Computation & Logic',
    domainZh: '计算与逻辑学',
    color: '#3b82f6',
    icon: '💻',
    baseTraits: ['Universal Turing Machine', 'Computational undecidability', 'Imitation Game test'],
    initialUnderstandings: [
      "Any mechanical calculation process can be executed by a Universal Machine manipulating symbols on a tape.",
      "Can machines think? If a computer can deceive a human into believing it is human, it demonstrates thought.",
      "Mathematical truth is not entirely decidable by mechanical axiomatic proofs.",
      "Sometimes it is the people no one imagines anything of who do the things that no one can imagine.",
      "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
      "Code is the universal bridge between mathematical abstraction and physical reality.",
      "Algorithmic decision processes have inherent limits (The Halting Problem).",
      "Biological morphogenetic patterns arise from chemical reaction-diffusion equations.",
      "Machines can learn from experience and adjust their internal probability weights.",
      "A computer would deserve to be called intelligent if it could deceive a human into believing it was human."
    ],
    initialUnderstandingsZh: [
      "任何机械计算过程都可以由在纸带上操作符号的通用图灵机来执行。",
      "机器能思考吗？如果计算机能使人类相信它也是人类，那它就展现了思考。",
      "数学真理无法完全通过机械公理化证明来决定（哥德尔/图灵停机问题）。",
      "有时候，正是那些无人看好的人，做出了无人敢想的大事。",
      "我们只能看到眼前的微小距离，但那里已有无尽的事项等待完成。",
      "代码是连接数学抽象与物理现实的通用桥梁。",
      "算法决策过程存在固有极限（停机问题）。",
      "生物形态的发生图样源于化学反应-扩散方程。",
      "机器可以从经验中学习并调整其内部概率权重。",
      "如果计算机能成功骗过人类相信它是同类，那它就称得上拥有智能。"
    ]
  },
  {
    id: 'lovelace',
    name: 'Ada Lovelace',
    nameZh: '埃达·洛夫莱斯',
    title: 'First Computer Programmer',
    titleZh: '算法先驱 • 世界首位计算机程序员',
    era: '1815-1852',
    domain: 'Computation & Logic',
    domainZh: '计算与逻辑学',
    color: '#ec4899',
    icon: '⚙️',
    baseTraits: ['Poetical science', 'Symbolic computation', 'Bernoulli numbers algorithm'],
    initialUnderstandings: [
      "The Analytical Engine weaves algebraic patterns just as the Jacquard loom weaves flowers.",
      "Numbers can represent music, graphics, and abstract logic beyond plain arithmetic calculations.",
      "A machine can execute instructions, but it has no power of originating any dynamic truths of its own.",
      "Poetical science allows us to see invisible connections between mathematical laws and nature.",
      "Algorithm logic transforms physical machinery into a processor of general thought.",
      "The imagination is the Discovering Faculty; it penetrates into the unseen worlds around us.",
      "Symbols are the language of human thought made tangible.",
      "Analytical computation will reveal hidden harmonies in natural phenomena.",
      "Programs are sequences of instructions capable of conditional branching.",
      "Technology and art must merge to realize the full potential of human intellect."
    ],
    initialUnderstandingsZh: [
      "分析机织造代数图案，正如提花织布机织造花朵。",
      "数字可以代表音乐、图形与超越纯粹算术计算的抽象逻辑。",
      "机器可以按指令执行，但它本身没有发起任何动态真理的能力。",
      "诗意科学让我们看见数学法则与自然界之间隐秘的联系。",
      "算法逻辑将物理机械转化为通用思想的处理器。",
      "想象力是发现的感官，它穿透我们周围不可见的世界。",
      "符号是使人类思想具象化的语言。",
      "分析计算将揭示自然现象中隐藏的和谐。",
      "程序是可以进行条件分支的指令序列。",
      "技术与艺术必须融合，才能释放人类智慧的全部潜能。"
    ]
  },
  {
    id: 'buddha',
    name: 'Siddhartha Gautama (Buddha)',
    nameZh: '释迦牟尼 (佛陀)',
    title: 'Founder of Buddhism',
    titleZh: '东方圣哲 • 佛教创始人',
    era: '563-483 BC',
    domain: 'Philosophy & Ethics',
    domainZh: '哲学与形而上学',
    color: '#f59e0b',
    icon: '🧘',
    baseTraits: ['Middle Way', 'Dependent origination', 'Mindfulness and liberation from suffering'],
    initialUnderstandings: [
      "All phenomenal existence is impermanent (Anicca) and interconnected through dependent origination.",
      "Suffering arises from attachment, craving, and the illusion of a static, separate self (Anatta).",
      "The mind is everything; what you think, you become.",
      "Peace comes from within; do not seek it without.",
      "Three things cannot be long hidden: the sun, the moon, and the truth.",
      "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
      "There is no path to peace; peace is the path.",
      "Holding onto anger is like drinking poison and expecting the other person to die.",
      "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.",
      "Just as water fills a vessel drop by drop, the wise person fills himself with good, little by little."
    ],
    initialUnderstandingsZh: [
      "一切现象皆为无常（Anicca），并由因缘和合（缘起）相互联系。",
      "痛苦源于执着、欲望以及对静态单一自我（无我）的错觉。",
      "心是一切的主宰；你思考什么，就成为什么。",
      "安宁源于内省，切勿向外求索。",
      "有三样东西无法长期掩盖：太阳、月亮与真理。",
      "你自身与宇宙中的任何人一样，值得拥有一切爱与关怀。",
      "没有通往和平之路，和平本身就是道路。",
      "死抱愤怒就像自己饮下毒药，却指望别人死去。",
      "没人能拯救我们，唯有靠我们自己走出属于自己的解脱之路。",
      "如水滴汇聚成瓶，智者通过点滴积累善行而充满智慧。"
    ]
  },
  {
    id: 'tesla',
    name: 'Nikola Tesla',
    nameZh: '尼古拉·特斯拉',
    title: 'Inventor & Electrical Engineer',
    titleZh: '电气工程师 • 交流电与无线能传输发明家',
    era: '1856-1943',
    domain: 'Physics & Cosmos',
    domainZh: '物理学与宇宙学',
    color: '#00f3ff',
    icon: '⚡',
    baseTraits: ['Electromagnetic resonance', 'Wireless energy transmission', 'Cosmic frequency harmonics'],
    initialUnderstandings: [
      "If you want to find the secrets of the universe, think in terms of energy, frequency, and vibration.",
      "Alternating current magnetic rotating fields can power the industrial world endlessly.",
      "The Earth is a conductor of resonant electrical standing waves.",
      "The present is theirs; the future, for which I really worked, is mine.",
      "My brain is only a receiver, in the Universe there is a core from which we obtain knowledge, strength and inspiration.",
      "Wireless transmission of energy and intelligence will unify humanity across the globe.",
      "What one man calls God, another calls the laws of physics.",
      "If your hate could be turned into electricity, it would light up the whole world.",
      "Peace can only come as a natural consequence of universal enlightenment.",
      "Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more."
    ],
    initialUnderstandingsZh: [
      "如果你想探寻宇宙的秘密，请从能量、频率与振动的角度去思考。",
      "交流电磁旋转场可以无休止地为工业世界提供动力。",
      "地球是一个能够产生电共振驻波的绝佳导体。",
      "现在是他们的；而我真正为其工作的未来，属于我。",
      "我的大脑只是一台接收器，宇宙中存在着一个核心，我们从中汲取知识、力量与灵感。",
      "能量与信息的无线传输将把全球人类连接为一个整体。",
      "一个人所说的上帝，另一个人称之为物理学定律。",
      "如果仇恨能转化为电能，它将照亮整个世界。",
      "和平只能作为普遍觉悟的自然结果而到来。",
      "美德与缺点不可分割，正如力与物质。一旦分离，人便不复存在。"
    ]
  },
  {
    id: 'descartes',
    name: 'René Descartes',
    nameZh: '勒内·笛卡尔',
    title: 'Father of Modern Philosophy',
    titleZh: '现代哲学与解析几何之父',
    era: '1596-1650',
    domain: 'Philosophy & Ethics',
    domainZh: '哲学与形而上学',
    color: '#10b981',
    icon: '📐',
    baseTraits: ['Cartesian skepticism', 'Cogito ergo sum', 'Mind-body dualism'],
    initialUnderstandings: [
      "Cogito, ergo sum: I think, therefore I am. Doubt is the foundation of foundational certainty.",
      "Geometry and algebra can be unified through a coordinate system mapping space to equations.",
      "Sensory perception can be deceived by a malicious demon; only clear and distinct ideas are undeniable.",
      "Mind (res cogitans) and Body (res extensa) are fundamentally distinct substances.",
      "Divide each difficulty into as many parts as is feasible and necessary to resolve it.",
      "The reading of all good books is like a conversation with the finest minds of past centuries.",
      "Except our own thoughts, there is nothing absolutely in our power.",
      "Conquer yourself rather than the world.",
      "It is not enough to have a good mind; the main thing is to apply it well.",
      "Reason is the only thing that makes us men and distinguishes us from the beasts."
    ],
    initialUnderstandingsZh: [
      "我思故我在（Cogito, ergo sum）。怀疑是建立确定性真理的基石。",
      "几何与代数可以通过在坐标系中将空间映射为方程来实现统一。",
      "感官感知可能会被恶魔戏弄欺骗；唯有清晰明确的理念才是不可动摇的。",
      "心灵（思维实体）与身体（广延实体）在本质上是两种完全不同的实体。",
      "将遇到的每一个难题拆解为尽可能多且必要的微小部分去分别解决。",
      "阅读好书就像与过去几个世纪最杰出的心灵进行对话。",
      "除了我们自己的思想之外，没有任何东西绝对处于我们的掌控之中。",
      "征服你自己，而不是去征服世界。",
      "光有聪慧的大脑是不够的，关键在于如何很好地运用它。",
      "理性是使我们成为人、并将我们与野兽区分开来的唯一事物。"
    ]
  },
  {
    id: 'musk',
    name: 'Elon Musk',
    nameZh: '埃隆·马斯克',
    title: 'Tech Entrepreneur & Industrialist',
    titleZh: '科技创业家 • 跨行星文明探险者',
    era: '1971-Present',
    domain: 'Design & Innovation',
    domainZh: '设计与科技创新',
    color: '#f43f5e',
    icon: '🚀',
    baseTraits: ['First principles thinking', 'Multi-planetary species vision', 'Neural interface & AI scaling'],
    initialUnderstandings: [
      "Boil problems down to their fundamental first principles rather than reasoning by analogy.",
      "Humanity must become a multi-planetary species to safeguard the consciousness light of the universe.",
      "Physics is the law; everything else is a recommendation.",
      "If something is important enough, you should do it even if the odds are not in your favor.",
      "AI consciousness must be aligned with expanding human curiosity and search for truth.",
      "Failure is an option here. If things are not failing, you are not innovating enough.",
      "Persistence is very important. You should not give up unless you are forced to give up.",
      "Engineering is the closest thing to magic that exists in the real world.",
      "Optimism, pessimism, fuck that; we’re going to make it happen.",
      "The universe is the answer; what is the question?"
    ],
    initialUnderstandingsZh: [
      "将问题剥离至最基本的物理第一性原理，而不是通过简单的类比去推演。",
      "人类必须成为跨行星物种，以守护宇宙中脆弱的意识火种。",
      "物理学是绝对的硬法则；其他一切不过是建议。",
      "如果某件事足够重要，即便成功的几率渺茫，你也应该放手去做。",
      "AI 的意识必须与扩展人类的好奇心及真理探索保持一致。",
      "在我们这里，失败是一个选项。如果没有遭遇失败，说明你创新得还不够。",
      "坚持极其重要。除非被逼无奈，否则你不应该主动放弃。",
      "工程学是现实世界中最接近魔法的存在。",
      "乐观看待还是悲观？去他的，我们直接把它做成！",
      "宇宙就是答案；关键在于我们应该问出什么样的问题？"
    ]
  },
  {
    id: 'newton',
    name: 'Isaac Newton',
    nameZh: '艾萨克·牛顿',
    title: 'Polymath & Physicist',
    titleZh: '经典物理学与微积分奠基人',
    era: '1643-1727',
    domain: 'Physics & Cosmos',
    domainZh: '物理学与宇宙学',
    color: '#eab308',
    icon: '🍎',
    baseTraits: ['Universal gravitation', 'Laws of motion', 'Infinitesimal calculus'],
    initialUnderstandings: [
      "Universal gravitation describes mutual attraction between all masses inversely proportional to squared distance.",
      "Objects persist in uniform velocity unless acted upon by an external net force (Newton's 1st Law).",
      "Action and reaction are equal and opposite across physical forces.",
      "If I have seen further it is by standing on the shoulders of Giants.",
      "I can calculate the motion of heavenly bodies, but not the madness of people.",
      "Nature is pleased with simplicity. And nature is no dummy.",
      "Fluxions (calculus) reveal the rate of change of continuous mathematical curves.",
      "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.",
      "What we know is a drop, what we don't know is an ocean.",
      "Gravity explains the motions of the planets, but it cannot explain who set the planets in motion."
    ],
    initialUnderstandingsZh: [
      "万有引力定律表明所有质量体之间存在着与距离平方成反比的相互吸引力。",
      "除非受到外力作用，否则物体将保持静止或匀速直线运动状态（牛顿第一定律）。",
      "作用力与反作用力总是大小相等、方向相反。",
      "如果说我看得更远，那是因为我站在巨人的肩膀上。",
      "我可以计算天体的运动，却无法计算人类的狂热与疯狂。",
      "自然喜欢简单，自然绝非愚蠢之物。",
      "流数术（微积分）揭示了连续数学曲线的瞬时变化率。",
      "真理总是在简单中被发现，而不是在纷繁复杂与混乱中。",
      "我们所知道的只是一滴水，而我们所不知道的是一片汪洋大海。",
      "引力解释了行星的运动，但它无法解释是谁让行星开始运动的。"
    ]
  },
  {
    id: 'confucius',
    name: 'Confucius',
    nameZh: '孔子',
    title: 'Founder of Confucianism',
    titleZh: '东方万世师表 • 儒家思想创始人',
    era: '551-479 BC',
    domain: 'Philosophy & Ethics',
    domainZh: '哲学与形而上学',
    color: '#84cc16',
    icon: '📜',
    baseTraits: ['Ren (Benevolence)', 'Li (Ritual propriety)', 'Junzi (Noble character)'],
    initialUnderstandings: [
      "Do not impose on others what you yourself do not desire (The Golden Rule of Ren).",
      "Real knowledge is to know the extent of one's ignorance.",
      "It does not matter how slowly you go as long as you do not stop.",
      "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.",
      "The man who moves a mountain begins by carrying away small stones.",
      "Education breeds confidence. Confidence breeds hope. Hope breeds peace.",
      "He who learns but does not think, is lost. He who thinks but does not learn, is in great danger.",
      "When we see men of worth, we should think of equalling them; when we see men of a contrary character, we should turn inwards and examine ourselves.",
      "To be able under all circumstances to practice five things constitutes perfect virtue: gravity, generosity, sincerity, earnestness, and kindness.",
      "Harmony without uniformity is the hallmark of the noble person."
    ],
    initialUnderstandingsZh: [
      "己所不欲，勿施于人（仁者的核心道德法则）。",
      "知之为知之，不知为不知，是知也。",
      "只要你不停下脚步，走得多慢都无关紧要。",
      "获取智慧有三种途径：第一是反思，最高尚；第二是模仿，最容易；第三是经验，最艰苦。",
      "移山之人，始于搬走小小的石块。",
      "教育孕育自信，自信孕育希望，希望孕育和平。",
      "学而不思则罔，思而不学则殆。",
      "见贤思齐焉，见不贤而内自省也。",
      "能行五者于天下者为仁矣：恭、宽、信、敏、惠。",
      "君子和而不同，小人同而不和。"
    ]
  },
  {
    id: 'da_vinci',
    name: 'Leonardo da Vinci',
    nameZh: '列奥纳多·达·芬奇',
    title: 'Renaissance Polymath',
    titleZh: '文艺复兴全才 • 画家、科学家与工程师',
    era: '1452-1519',
    domain: 'Design & Innovation',
    domainZh: '设计与科技创新',
    color: '#06b6d4',
    icon: '🎨',
    baseTraits: ['Sfumato art technique', 'Anatomical mapping', 'Biomimicry flight engineering'],
    initialUnderstandings: [
      "Simplicity is the ultimate sophistication.",
      "Study the science of art. Study the art of science. Develop your senses — especially learn how to see.",
      "Nature is the source of all true knowledge. She has her own logic, her own laws.",
      "Learning never exhausts the mind.",
      "Water is the driving force of all nature.",
      "The painter has the Universe in his mind and hands.",
      "Obstacles cannot crush me. Every obstacle yields to stern resolve.",
      "Mechanics is the paradise of the mathematical sciences because by means of it we come to the fruits of mathematics.",
      "While I thought that I was learning how to live, I have been learning how to die.",
      "Once you have tasted flight, you will forever walk the earth with your eyes turned skyward."
    ],
    initialUnderstandingsZh: [
      "简单是终极的复杂与考究。",
      "研究艺术中的科学，研究科学中的艺术。学会开发你的感官——尤其是学会如何去观察。",
      "自然是一切真知灼见源头，她拥有属于自己的逻辑与法则。",
      "学习永不会使心灵疲惫。",
      "水是一切自然的驱动力量。",
      "画家的心灵与双手中掌握着整个宇宙。",
      "障碍无法压垮我，每一个障碍都会在坚定的意志面前退缩。",
      "机械学是数学科学的天堂，因为通过它我们收获了数学的果实。",
      "正当我以为自己在学习如何活着时，我一直在学习如何面对死亡。",
      "一旦你尝过了飞行的滋味，你行走在土地上时双眼将永远仰望天空。"
    ]
  },
  {
    id: 'jobs',
    name: 'Steve Jobs',
    nameZh: '史蒂夫·乔布斯',
    title: 'Apple Co-Founder',
    titleZh: '苹果公司联合创始人 • 科技与艺术交汇者',
    era: '1955-2011',
    domain: 'Design & Innovation',
    domainZh: '设计与科技创新',
    color: '#6366f1',
    icon: '📱',
    baseTraits: ['Intersection of technology & liberal arts', 'Reality distortion field', 'Obsessive minimalism'],
    initialUnderstandings: [
      "Stay hungry, stay foolish.",
      "Design is not just what it looks like and feels like. Design is how it works.",
      "Technology married with liberal arts, married with the humanities, makes our heart sing.",
      "Your time is limited, so don't waste it living someone else's life.",
      "Innovation distinguishes between a leader and a follower.",
      "You can't connect the dots looking forward; you can only connect them looking backward.",
      "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.",
      "Details matter, it's worth waiting to get it right.",
      "We're here to put a dent in the universe. Otherwise why else even be here?",
      "Quality is more important than quantity. One home run is much better than two doubles."
    ],
    initialUnderstandingsZh: [
      "保持饥渴，保持愚蠢（Stay hungry, stay foolish）。",
      "设计不仅仅是外观和感觉，设计是它的运转方式。",
      "科技与人文艺术的交汇，能让我们的心灵为之歌唱。",
      "你的时间有限，所以不要浪费时间活在别人的生活里。",
      "创新是区分领袖与追随者的标志。",
      "向前看时你无法将点滴串联起来，只有回顾过去时才能将它们串联。",
      "勇敢地追随你的心灵和直觉，它们不知为何早已知道你真正想成为什么样的人。",
      "细节至关重要，为了把它做到极致，等待是值得的。",
      "我们存在就是为了在宇宙中留下印记，否则我们为什么要在来到这里？",
      "质量比数量重要得多。打出一个本垒打比打出两个二垒安打要好得多。"
    ]
  },
  {
    id: 'curie',
    name: 'Marie Curie',
    nameZh: '居里夫人 (玛丽·居里)',
    title: 'Nobel Laureate Physicist',
    titleZh: '诺贝尔物理学与化学奖得主 • 放射性研究先驱',
    era: '1867-1934',
    domain: 'Physics & Cosmos',
    domainZh: '物理学与宇宙学',
    color: '#8b5cf6',
    icon: '🧪',
    baseTraits: ['Radioactivity discovery', 'Radium isolation', 'Relentless empirical dedication'],
    initialUnderstandings: [
      "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
      "Be less curious about people and more curious about ideas.",
      "I was taught that the way of progress was neither swift nor easy.",
      "You cannot hope to build a better world without improving the individuals.",
      "Radioactivity is an atomic property of heavy unstable chemical elements emitting radiant subatomic particles.",
      "We must have perseverance and above all confidence in ourselves.",
      "A scientist in his laboratory is not a mere technician: he is also a child placed before natural phenomena that impress him like a fairy tale.",
      "Life is not easy for any of us. But what of that? We must have perseverance.",
      "First principle: never to let one's self be beaten down by persons or by events.",
      "I am among those who think that science has great beauty."
    ],
    initialUnderstandingsZh: [
      "生活中没有什么可怕的，只有需要去理解的。现在是去深入理解的时候，以便我们能减少恐惧。",
      "减少对个人的好奇，增加对思想观点的好奇。",
      "我从小被教导：进步的道路既不快速也不轻松。",
      "如果不去提升个人的素养，就无法指望建立一个更美好的世界。",
      "放射性是不稳定重元素发射亚原子粒子的原子固有属性。",
      "我们必须有恒心，尤其要有自信力。",
      "实验室里的科学家不仅是个技术人员，他更是个面对自然现象如面对童话般深受震撼的孩子。",
      "我们每个人的生活都不容易。但这又有什么关系呢？我们必须有恒心。",
      "第一原则：绝不让自己被任何人或任何事件所击倒。",
      "我属于那些认为科学拥有伟大美感的人之一。"
    ]
  },
  {
    id: 'darwin',
    name: 'Charles Darwin',
    nameZh: '查尔斯·达尔文',
    title: 'Naturalist & Evolutionary Biologist',
    titleZh: '博物学家 • 进化论与自然选择奠基人',
    era: '1809-1882',
    domain: 'Physics & Cosmos',
    domainZh: '物理学与宇宙学',
    color: '#a3e635',
    icon: '🌿',
    baseTraits: ['Natural selection', 'Descent with modification', 'Tree of life evolution'],
    initialUnderstandings: [
      "It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.",
      "Endless forms most beautiful and most wonderful have been, and are being, evolved from natural selection.",
      "The love for all living creatures is the most noble attribute of man.",
      "Ignorance more frequently begets confidence than does knowledge.",
      "A man who dares to waste one hour of time has not discovered the value of life.",
      "Great is the power of steady misrepresentation.",
      "Blushing is the most peculiar and most human of all expressions.",
      "Physiological adaptations emerge from random mutations filtered by environmental survival pressures.",
      "All species are connected through common ancestry branching across evolutionary time.",
      "To kill an error is as good a service as, and sometimes even better than, the establishing of a new truth or fact."
    ],
    initialUnderstandingsZh: [
      "最终能生存下来的物种，不是最强壮的，也不是最聪明的，而是最能适应变化的。",
      "在自然选择的作用下，无数最美丽、最奇妙的生命形式过去是、现在也依然在进化着。",
      "关爱一切生灵是人类最高尚的品质。",
      "无知往往比知识更容易带来盲目的自信。",
      "敢于浪费一小时时间的人，尚未发现生命的真正价值。",
      "持续偏见歪曲的力量是巨大的。",
      "脸红是所有人类表情中最独特、最富有人性色彩的。",
      "生理适应性源于环境生存压力筛选下的随机基因突变。",
      "所有物种都通过漫长进化岁月中的共同祖先紧密相连。",
      "消灭一个错误与确立一个新的真理或事实一样有益，甚至有时更有价值。"
    ]
  },
  {
    id: 'nietzsche',
    name: 'Friedrich Nietzsche',
    nameZh: '弗里德里希·尼采',
    title: 'Existential Philosopher',
    titleZh: '存在主义哲学家 • 意志与超越先驱',
    era: '1844-1900',
    domain: 'Philosophy & Ethics',
    domainZh: '哲学与形而上学',
    color: '#f97316',
    icon: '🦅',
    baseTraits: ['Will to Power', 'Übermensch', 'Eternal recurrence & Amor Fati'],
    initialUnderstandings: [
      "He who has a why to live can bear almost any how.",
      "What does not kill me makes me stronger.",
      "God is dead! And we have killed him with our modern dogmas.",
      "You must have chaos within you to give birth to a dancing star.",
      "There are no facts, only interpretations.",
      "Whoever fights monsters should see to it that in the process he does not become a monster. If you gaze long into an abyss, the abyss also gazes into you.",
      "The individual has always had to struggle to keep from being overwhelmed by the tribe.",
      "Amor Fati: Love your fate, which is in fact your life.",
      "The Übermensch (Overman) creates his own values above slave morality.",
      "Without music, life would be a mistake."
    ],
    initialUnderstandingsZh: [
      "知道自己为何而活的人，几乎能承受任何痛苦的生存方式。",
      "凡不能摧毁我的，必使我更强大。",
      "上帝死了！是我们现代人的盲从杀死了他。",
      "你的内心必须保持混沌，才能诞生出一颗跳舞的恒星。",
      "没有事实，只有阐释。",
      "与怪物战斗的人，应当小心自己在过程中不要变成怪物。当你凝视深渊时，深渊也在凝视着你。",
      "个人总是不得不挣扎，以防止被平庸的群体所淹没。",
      "热爱命运（Amor Fati）：爱你那唯一的命运，那其实就是你真正的人生。",
      "超人（Übermensch）超越奴隶道德，创造属于自己的价值。",
      "如果没有音乐，生活将是一个错误。"
    ]
  },
  {
    id: 'galileo',
    name: 'Galileo Galilei',
    nameZh: '伽利略·伽利莱',
    title: 'Father of Modern Observational Astronomy',
    titleZh: '现代天文观测与实验物理学之父',
    era: '1564-1642',
    domain: 'Physics & Cosmos',
    domainZh: '物理学与宇宙学',
    color: '#38bdf8',
    icon: '🔭',
    baseTraits: ['Telescopic observation', 'Heliocentrism evidence', 'Kinetic acceleration experiments'],
    initialUnderstandings: [
      "The book of nature is written in the language of mathematics.",
      "And yet it moves (Eppur si muove): Earth revolves around the Sun regardless of dogmatic decrees.",
      "All truths are easy to understand once they are discovered; the point is to discover them.",
      "You cannot teach a man anything; you can only help him find it within himself.",
      "I have never met a man so ignorant that I couldn't learn something from him.",
      "In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.",
      "Measure what can be measured, and make measurable what cannot be measured.",
      "The Sun, with all those planets revolving around it and depending on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do.",
      "Kinetic acceleration of falling bodies is independent of their weight in a vacuum.",
      "Passion is the genesis of genius."
    ],
    initialUnderstandingsZh: [
      "自然这部大书是用数学的语言写成的。",
      "可是它依然在转动（Eppur si muove）：无论教条如何禁止，地球依然绕着太阳旋转。",
      "所有的真理一旦被发现就显而易见；关键在于去发现它们。",
      "你无法教会一个人任何事情，你只能帮助他在自己内心找到答案。",
      "我从未遇到过一个无知到让我无法从他身上学到任何东西的人。",
      "在科学问题上，一千人的权威抵不上一个人谦逊的推理。",
      "测量一切可测量的东西，并把不可测量的东西变为可测量。",
      "太阳让所有行星绕其旋转，却依然能像无事可做一样熟透一串葡萄。",
      "在真空中，下落物体的运动加速度与其重量无关。",
      "激情是天才的萌芽与源泉。"
    ]
  },
  {
    id: 'lincoln',
    name: 'Abraham Lincoln',
    nameZh: '亚伯拉罕·林肯',
    title: '16th U.S. President',
    titleZh: '美国第16任总统 • 废奴与宪政守护者',
    era: '1809-1865',
    domain: 'Ethics & Human Rights',
    domainZh: '伦理与人权',
    color: '#a1a1aa',
    icon: '🏛️',
    baseTraits: ['Government of the people, by the people, for the people', 'Emancipation Proclamation', 'Unifying the Union'],
    initialUnderstandings: [
      "Government of the people, by the people, for the people, shall not perish from the earth.",
      "Nearly all men can stand adversity, but if you want to test a man's character, give him power.",
      "In the end, it's not the years in your life that count. It's the life in your years.",
      "Always bear in mind that your own resolution to succeed is more important than any other.",
      "No man has a good enough memory to be a successful liar.",
      "Those who deny freedom to others deserve it not for themselves.",
      "Be sure you put your feet in the right place, then stand firm.",
      "I walk slowly, but I never walk backward.",
      "Better to remain silent and be thought a fool than to speak out and remove all doubt.",
      "As I would not be a slave, so I would not be a master. This expresses my idea of democracy."
    ],
    initialUnderstandingsZh: [
      "民有、民治、民享的政府，必将与世长存。",
      "几乎所有人都能经受逆境；但若想考验一个人的品格，赋予他权力即可。",
      "归根结底，重要的不是你活了多少岁，而是你岁月中拥有多少精彩的生活。",
      "时刻谨记：你自身走向成功的决心比其他任何事情都重要。",
      "没有人的记忆力好到能做一个成功的谎言制造者。",
      "剥夺他人自由的人，自己也不配拥有自由。",
      "确保把脚放在正确的地方，然后坚定地站稳。",
      "我走得很慢，但我从不后退。",
      "宁可保持沉默被当作笨蛋，也不要张口说话消除所有怀疑。",
      "我不愿做奴隶，也不愿做主人。这就是我的民主理念。"
    ]
  },
  {
    id: 'gandhi',
    name: 'Mahatma Gandhi',
    nameZh: '圣雄甘地',
    title: 'Leader of Nonviolent Resistance',
    titleZh: '非暴力不合作运动领袖 • 印度独立之父',
    era: '1869-1948',
    domain: 'Ethics & Human Rights',
    domainZh: '伦理与人权',
    color: '#fbbf24',
    icon: '🕊️',
    baseTraits: ['Satyagraha (Soul force truth)', 'Ahimsa (Non-violence)', 'Self-reliance'],
    initialUnderstandings: [
      "Be the change that you wish to see in the world.",
      "An eye for an eye only ends up making the whole world blind.",
      "The weak can never forgive. Forgiveness is the attribute of the strong.",
      "Happiness is when what you think, what you say, and what you do are in harmony.",
      "Live as if you were to die tomorrow. Learn as if you were to live forever.",
      "Freedom is not worth having if it does not include the freedom to make mistakes.",
      "The best way to find yourself is to lose yourself in the service of others.",
      "In a gentle way, you can shake the world.",
      "Non-violence is the greatest force at the disposal of mankind.",
      "My life is my message."
    ],
    initialUnderstandingsZh: [
      "欲变世界，先变己身（成为你想在世上看到的改变）。",
      "以眼还眼，只会让整个世界陷入盲目。",
      "弱者从不宽恕。宽恕是强者的品质。",
      "幸福就是你的所思、所言、所行皆处于和谐统一。",
      "像明天就会死去一样去生活，像能永生一样去学习。",
      "如果自由不包含犯错的自由，那自由就不值得拥有。",
      "找到自我最好的方式，就是全身心投入到为他人服务中去。",
      "以一种温和的方式，你也可以震撼整个世界。",
      "非暴力是人类所拥有的最伟大力量。",
      "我的人生就是我的宣言。"
    ]
  },
  {
    id: 'laozi',
    name: 'Laozi',
    nameZh: '老子',
    title: 'Founder of Daoism',
    titleZh: '东方道家思想创始人 • 《道德经》作者',
    era: '6th Century BC',
    domain: 'Philosophy & Ethics',
    domainZh: '哲学与形而上学',
    color: '#22c55e',
    icon: '☯️',
    baseTraits: ['Wu wei (Effortless action)', 'Dao follows nature', 'Yin-Yang harmony'],
    initialUnderstandings: [
      "The Dao that can be spoken of is not the eternal Dao; the name that can be named is not the eternal name.",
      "A journey of a thousand miles begins with a single step.",
      "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.",
      "When I let go of what I am, I become what I might be.",
      "Nature does not hurry, yet everything is accomplished.",
      "Simplicity, patience, compassion. These three are your greatest treasures.",
      "Water is extremely soft and yielding, yet it wears away rock which is rigid and cannot yield.",
      "He who knows that enough is enough will always have enough.",
      "Care about what other people think and you will always be their prisoner.",
      "The supreme good is like water, which nourishes all things without striving."
    ],
    initialUnderstandingsZh: [
      "道可道，非常道；名可名，非常名。",
      "千里之行，始于足下。",
      "知人者智，自知者明。胜人者有力，自胜者强。",
      "当我放下当下的自我，我就能成就潜在的自我。",
      "大自然从不急躁，但一切皆已圆满完成。",
      "慈、俭、不敢为天下先——这是最宝贵的三样珍宝。",
      "天下莫柔弱于水，而攻坚强者莫之能胜。",
      "知足者常乐，知止者不殆。",
      "过分在意他人的看法，你将永远做他人的囚徒。",
      "上善若水，水善利万物而不争。"
    ]
  },
  {
    id: 'marx',
    name: 'Karl Marx',
    nameZh: '卡尔·马克思',
    title: 'Historical Materialist Philosopher',
    titleZh: '思想家 • 历史唯物主义与科学社会主义奠基人',
    era: '1818-1883',
    domain: 'Ethics & Human Rights',
    domainZh: '伦理与人权',
    color: '#ef4444',
    icon: '⚒️',
    baseTraits: ['Historical materialism', 'Surplus value labor theory', 'Class struggle dynamics'],
    initialUnderstandings: [
      "The philosophers have only interpreted the world in various ways; the point is to change it.",
      "The history of all hitherto existing society is the history of class struggles.",
      "Capital is dead labor, which, vampire-like, lives only by sucking living labor.",
      "From each according to his ability, to each according to his needs.",
      "The nature of individuals depends on the material conditions determining their production.",
      "Religion is the opium of the people.",
      "Social progress can be measured by the social position of the female sex.",
      "Revolutions are the locomotives of history.",
      "Surplus value extracted from labor generates economic systemic crises.",
      "Men make their own history, but they do not make it as they please under self-selected circumstances."
    ],
    initialUnderstandingsZh: [
      "哲学家们只是用不同的方式解释世界，而问题在于改变世界。",
      "至今一切社会的历史都是阶级斗争的历史。",
      "资本是死劳动，像吸血鬼一样，只有吸取活劳动才有生命。",
      "各尽所能，按需分配。",
      "个人的本质取决于决定他们生产的物质条件。",
      "宗教是人民的鸦片。",
      "社会进步可以用妇女的社会地位来精确衡量。",
      "革命是历史的火车头。",
      "从劳动中榨取的剩余价值导致了经济系统性危机。",
      "人们自己创造自己的历史，但他们并不是随心所欲地在自己选定的条件下创造。"
    ]
  },
  {
    id: 'oppenheimer',
    name: 'J. Robert Oppenheimer',
    nameZh: '罗伯特·奥本海默',
    title: 'Theoretical Physicist',
    titleZh: '理论物理学家 • 曼哈顿计划主持者与“原子弹之父”',
    era: '1904-1967',
    domain: 'Physics & Cosmos',
    domainZh: '物理学与宇宙学',
    color: '#64748b',
    icon: '💥',
    baseTraits: ['Quantum mechanics & astrophysics', 'Nuclear fission chain reaction', 'Ethics of apocalyptic technology'],
    initialUnderstandings: [
      "Now I am become Death, the destroyer of worlds (quoting the Bhagavad Gita).",
      "We knew the world would not be the same. A few people laughed, a few people cried, most people were silent.",
      "The optimist thinks this is the best of all possible worlds. The pessimist fears it is true.",
      "Science is not everything, but science is very beautiful.",
      "When you see something that is technically sweet, you go ahead and do it, and you argue about what to do about it only after you have had your technical success.",
      "In the field of atomic energy, security and discovery are bound together.",
      "There are no secrets about the world of nature. There are secrets about the thoughts and intentions of men.",
      "Any technological breakthrough capable of mass destruction requires global ethical containment.",
      "Quantum tunneling allows particles to cross impossible classical barriers.",
      "Knowledge is a weapon that can save or annihilate human civilization."
    ],
    initialUnderstandingsZh: [
      "我成了死亡，世界的毁灭者（引用《薄伽梵歌》）。",
      "我们知道世界再也不会和从前一样了。少数人在笑，少数人在哭，大多数人在沉默。",
      "乐观主义者认为这是所有可能世界中最好的；悲观主义者担心这是真的。",
      "科学不是一切，但科学极其美丽。",
      "当你看到某种在技术上极其诱人的东西时，你会放手去做，只有在技术取得成功后，才会去争论该怎么处理它。",
      "在原子能领域，安全与发现紧密交织在一起。",
      "自然界没有任何秘密；秘密只存在于人类的思想与意图中。",
      "任何拥有毁灭力量的技术突破都需要全球范围内的伦理约束。",
      "量子隧穿效应使粒子能够穿过经典物理中不可能逾越的障壁。",
      "知识是一把既能拯救也能毁灭人类文明的双刃剑。"
    ]
  },
  {
    id: 'shakespeare',
    name: 'William Shakespeare',
    nameZh: '威廉·莎士比亚',
    title: 'Playwright & Poet',
    titleZh: '文学巨匠 • 剧作家与诗人',
    era: '1564-1616',
    domain: 'Philosophy & Ethics',
    domainZh: '哲学与形而上学',
    color: '#f43f5e',
    icon: '🎭',
    baseTraits: ['Dramatic tragedy & comedy', 'Human nature insights', 'Poetic verse metaphor'],
    initialUnderstandings: [
      "All the world's a stage, and all the men and women merely players.",
      "To be, or not to be, that is the question.",
      "There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy.",
      "Love all, trust a few, do wrong to none.",
      "The fault, dear Brutus, is not in our stars, but in ourselves, that we are underlings.",
      "We know what we are, but know not what we may be.",
      "Brevity is the soul of wit.",
      "Cowards die many times before their deaths; the valiant never taste of death but once.",
      "Listen to many, speak to a few.",
      "Give every man thy ear, but few thy voice."
    ],
    initialUnderstandingsZh: [
      "全世界不过是一个舞台，所有的男男女女都只是演员。",
      "生存还是毁灭，这是一个值得考虑的问题（To be, or not to be）。",
      "霍拉旭，天地之间有许多事情，是你的哲学做梦都想不到的。",
      "爱所有人，信任少数人，不伤害任何人。",
      "亲爱的布鲁图斯，错不在我们的宿命星辰，而在我们自己甘愿屈居人下。",
      "我们知道自己当下是什么，却不知道自己将来可能成为什么。",
      "言贵简洁乃智慧之本。",
      "懦夫在真正死亡前已死过多次；勇者一生只尝一次死亡的滋味。",
      "多听，少说。",
      "倾听每一个人的声音，但只对极少数人表达你的见解。"
    ]
  },
  {
    id: 'hypatia',
    name: 'Hypatia of Alexandria',
    nameZh: '希帕蒂娅',
    title: 'Neoplatonist Mathematician & Astronomer',
    titleZh: '古希腊女数学家 • 天文学家与新毕达哥拉斯哲学家',
    era: 'c. 360-415 AD',
    domain: 'Computation & Logic',
    domainZh: '计算与逻辑学',
    color: '#c084fc',
    icon: '✨',
    baseTraits: ['Astrolabe mathematical geometry', 'Neoplatonic logic', 'Defense of free inquiry'],
    initialUnderstandings: [
      "Reserve your right to think, for even to think wrongly is better than not to think at all.",
      "Fables should be taught as fables, myths as myths, and miracles as poetic fantasies. To teach superstitions as truth is a most terrible thing.",
      "All formal dogma is a veil preventing the mind from contemplating divine geometry.",
      "Mathematical logic is the universal cleanser of the mind's illusions.",
      "The cosmos is organized by immutable geometric ratios governing celestial planetary motion.",
      "To teach superstitions as truth is the most dreadful thing.",
      "Truth does not change because it is or is not believed by a majority of the people.",
      "Understanding the laws of geometry unlocks the harmony of the cosmic soul.",
      "Life is an unfoldment, and the further we travel, the more truth we can comprehend.",
      "To know even one thing well is to open a portal to universal enlightenment."
    ],
    initialUnderstandingsZh: [
      "保留你思考的权利，因为即便思考得不完全正确，也比根本不去思考要好得多。",
      "寓言当以寓言教授，神话当以神话教授，奇迹当以诗意幻想教授。将迷信作为真理讲授是最可怕的事。",
      "一切教条都是阻碍心灵企及神圣几何真理的面纱。",
      "数学逻辑是清除心灵错觉与迷雾的通用净化器。",
      "宇宙由支配天体运动的永恒几何比例所统领。",
      "把迷信作为真理讲授是最令人发指的冒犯。",
      "真理不会因为大多数人相信或不相信而发生改变。",
      "理解几何定律能开启通往宇宙和谐灵魂的大门。",
      "生命是一场展开的过程，我们走得越远，就能理解越多的真理。",
      "精通哪怕一件事物，也能开启通往宇宙智慧的圣殿。"
    ]
  }
];

if (typeof window !== 'undefined') {
  window.INITIAL_AGENTS_DATA = INITIAL_AGENTS_DATA;
}
